// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGwD5ARU4znKBfo3vkW4IBCCkagKgfNAo',
    appId: '1:280427738256:android:f06c25e3f564e62c295415',
    messagingSenderId: '280427738256',
    projectId: 'firbaseexampleproject',
    storageBucket: 'firbaseexampleproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvMKJvXlBL4p1mDeJmGGvG3eLj4xu-6u8',
    appId: '1:280427738256:ios:7579158671602763295415',
    messagingSenderId: '280427738256',
    projectId: 'firbaseexampleproject',
    storageBucket: 'firbaseexampleproject.firebasestorage.app',
    androidClientId: '280427738256-0bee4pvb0aut2j2p29h89j6aj87aj04t.apps.googleusercontent.com',
    iosClientId: '280427738256-ig507if0u6sbpimc6pdsaob32v4dkbc2.apps.googleusercontent.com',
    iosBundleId: 'com.example.orderTracking',
  );
}
